=== apache/struts/core/src/main/resources/xwork-validator-1.0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  XWork Validators DTD.
  Used the following DOCTYPE.
  
  <!DOCTYPE validators PUBLIC 
  		"-//Apache Struts//XWork Validator 1.0//EN"
  		"http://struts.apache.org/dtds/xwork-validator-1.0.dtd">
-->


<!ELEMENT validators (field*,validator*)>

<!ELEMENT field (field-validator+)>
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT field-validator (param*, message)>
<!ATTLIST field-validator
	type CDATA #REQUIRED
>

<!ELEMENT validator (param*, message)>
<!ATTLIST validator
	type CDATA #REQUIRED
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param
    name CDATA #REQUIRED
>

<!ELEMENT message (#PCDATA)>
<!ATTLIST message
    key CDATA #IMPLIED
>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/SimpleAction-validationAlias-validation.xml
<!DOCTYPE validators PUBLIC "-//Apache Struts//XWork Validator 1.0//EN" "http://struts.apache.org/dtds/xwork-validator-1.0.dtd">
<validators>
    <field name="baz">
        <field-validator type="required">
            <message>You must enter a value for baz.</message>
        </field-validator>
        <field-validator type="int">
            <param name="min">2</param>
            <param name="max">4</param>
            <message>baz out of range.</message>
        </field-validator>
    </field>
</validators>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/test/Equidae-validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
-->
<!DOCTYPE validators PUBLIC "-//Apache Struts//XWork Validator 1.0//EN" "http://struts.apache.org/dtds/xwork-validator-1.0.dtd">
<validators>
    <field name="horse">
        <field-validator type="requiredstring">
            <param name="trim">false</param>
            <message>noTrim</message>
        </field-validator>
        <field-validator type="requiredstring">
            <param name="trim">true</param>
            <message>trim</message>
        </field-validator>
    </field>

    <field name="cow">
        <field-validator type="stringlength">
            <param name="trim">false</param>
            <param name="minLength">5</param>
            <message>noTrim-min5</message>
        </field-validator>
        <field-validator type="stringlength">
            <param name="trim">false</param>
            <param name="minLength">5</param>
            <param name="maxLength">10</param>
            <message>noTrim-min5-max10</message>
        </field-validator>
        <field-validator type="stringlength">
            <param name="trim">false</param>
            <param name="maxLength">10</param>
            <message>noTrim-max10</message>
        </field-validator>
    </field>

    <field name="donkey">
        <field-validator type="stringlength">
            <param name="trim">true</param>
            <param name="minLength">5</param>
            <message>trim-min5</message>
        </field-validator>
        <field-validator type="stringlength">
            <param name="trim">true</param>
            <param name="minLength">5</param>
            <param name="maxLength">10</param>
            <message>trim-min5-max10</message>
        </field-validator>
        <field-validator type="stringlength">
            <param name="trim">true</param>
            <param name="maxLength">10</param>
            <message>trim-max10</message>
        </field-validator>
    </field>

</validators>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/test/SimpleAction2-validation.xml
<!DOCTYPE validators PUBLIC "-//Apache Struts//XWork Validator 1.0//EN" "http://struts.apache.org/dtds/xwork-validator-1.0.dtd">
<validators>
    <field name="count">
        <field-validator type="required">
            <message>You must enter a value for count.</message>
        </field-validator>
        <field-validator type="int">
            <param name="min">0</param>
            <param name="max">5</param>
            <message>count must be between ${min} and ${max}, current value is ${count}.</message>
        </field-validator>
    </field>
</validators>

=== apache/struts/webapps/showcase/src/java/org/apache/struts/action2/showcase/action/EmployeeAction-validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators PUBLIC "-//OpenSymphony Group//XWork Validator 1.0//EN" "http://www.opensymphony.com/xwork/xwork-validator-1.0.dtd">
<validators>
    <!-- Field-Validator Syntax -->
    <field name="currentEmployee.empId">
        <field-validator type="required">
            <message key="employee.id.required"/>
        </field-validator>
    </field>
    <field name="currentEmployee.lastName">
        <field-validator type="requiredstring">
            <param name="trim">true</param>
            <message key="employee.lastName.required"/>
        </field-validator>
    </field>
    <field name="currentEmployee.birthDate">
        <field-validator type="required">
            <message key="employee.birthDate.required"/>
        </field-validator>
    </field>
</validators>

=== apache/struts/core/src/test/resources/com/opensymphony/xwork2/TestBean-visitorChildValidation-validation.xml
<!DOCTYPE validators PUBLIC "-//Apache Struts//XWork Validator 1.0//EN" "http://struts.apache.org/dtds/xwork-validator-1.0.dtd">
<validators>
    <field name="birth">
        <field-validator type="date">
            <param name="min">01/01/1970</param>
            <message>You must have been born after 1970.</message>
        </field-validator>
    </field>
    <field name="child">
        <field-validator type="visitor">
            <message>child bean: </message>
        </field-validator>
    </field>
</validators>

=== apache/struts/apps/showcase/src/main/resources/org/apache/struts2/showcase/action/EmployeeAction-validation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators PUBLIC "-//Apache Struts//XWork Validator 1.0//EN" "http://struts.apache.org/dtds/xwork-validator-1.0.dtd">
<validators>
    <!-- Field-Validator Syntax -->
    <field name="currentEmployee.empId">
        <field-validator type="required">
            <message key="employee.id.required"/>
        </field-validator>
    </field>
    <field name="currentEmployee.lastName">
        <field-validator type="requiredstring">
            <param name="trim">true</param>
            <message key="employee.lastName.required"/>
        </field-validator>
    </field>
    <field name="currentEmployee.birthDate">
        <field-validator type="required">
            <message key="employee.birthDate.required"/>
        </field-validator>
    </field>
</validators>
